language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - pip install black
  - echo "Black formatting check"
  - black --check *.py

install:
  - python thirdparty/virtualenv.pyz --never-download --no-periodic-update .
  - bin/pip install -e .[test]

script:
  - bin/isort --check-only src/ tests/
  - bin/py.test -vvs
